local cmd = require('cmd')
local filetree = require('filetree')
local util = require('util')

-- TODO better than a hard-coded path
local script_path = 'node /home/thomas/Perso/misc/screenshot/screenshot_and_pdf.js'

-- DocStore POST hook
function hook (doc)
  -- Call the script to generate the screenshot and the PDF
  local filename = util.random_string(16)
  print('URL')
  print(doc.url)
  local err = cmd.run(script_path .. ' '.. doc.url ..' ' .. filename)

  if err ~= '' then
    print(err)
    return nil
  end

  -- Optimize the PNG
  local err = cmd.run('optipng ' .. filename .. '.png')
  if err ~= '' then
    print(err)
    return nil
  end

  -- Upload the screenshot and the PDF generated by Chrome Headless
  local screenshot = filetree.put_file('/tmp/' .. filename .. '.png', 'screenshot.png')
  local pdf = filetree.put_file('/tmp/' .. filename .. '.pdf', 'print.pdf')
  util.delete_file(filename .. '.pdf')
  util.delete_file(filename .. '.png')
  -- FIXME(tsileo): unlink the files

  -- Update the doc
  doc.backup = {}
  doc.backup.screenshot = '@filetree/ref:' .. screenshot
  doc.backup.pdf = '@filetree/ref:' .. pdf

  return doc
end

return hook
